# This is a basic workflow to help you get started with Actions

name: CI

# charge le token secret
env:
  TOKEN: ${{ secrets.TOKEN }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "0 */12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # se deplace a la racine du projet
      - name: se deplace a la racine du projet
        run: cd ..
      # Runs a single command using the runners shell
      - name: install node dependencies
        run: npm install

      - name: se deplace dans le dossier stats
        run: cd stats

      # Runs a set of commands using the runners shell
      - name: genere les stats de la partie frontend
        run: node index.js frontend

      - name: genere les stats de la partie backend
        run: node index.js backend

      - name: Commit to the repo
        run: |
          cd ../profile
          git config --global user.name "L3PO"
          git config --global user.email "bot@antoninrousseau.fr"
          git pull
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m 'Update generated files' || echo
          git push
